version: "3.9"
services:
  haproxy:
    container_name: haproxy
    image: haproxy:2.8.3
    volumes:
      - ./files/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "81:81"
      - "8081:8081"
      - "6443:6443"
networks:
  host:
    name: kind
    external: true
